### PR TITLE
Add support for riscv64 architecture

### PR DESCRIPTION
**Pull request by r-value**
This patch enables the driver to compile on riscv64 machines.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 58e5d137c97539a6158583287898f7f320bc4275
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev e553debed3e5893837256df4025d9c4fa1d51b4a</li>
<li>SPVGEN: dev fa39b110650bc72fd7fda54af621e69306036888</li>
<li>XGL: dev 36c5637649089bf65d42c36b431f47c170b57276</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev eb9d3792bdfda0b6fb94af6bd9989cad51842403</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/202392)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 38237/67464 (56.7%)</li>
<li>Failed: 0/67464 (0.0%)</li>
<li>Not Supported: 29227/67464 (43.3%)</li><li>Warnings: 0/67464 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 38075/67464 (56.4%)</li>
<li>Failed: 0/67464 (0.0%)</li>
<li>Not Supported: 29389/67464 (43.6%)</li><li>Warnings: 0/67464 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39235/67464 (58.2%)</li>
<li>Failed: 0/67464 (0.0%)</li>
<li>Not Supported: 28229/67464 (41.8%)</li><li>Warnings: 0/67464 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by JakeMerdichAMD** [comment]
Looks like TARGET_##_OS is only used within this file, and the only place it [actually makes a difference](https://github.com/GPUOpen-Drivers/pal/blob/dev/src/core/imported/vam/inc/vambasictypes.h#L157) can have the platform differences replaced with `uintptr_t`.

Your fix will work for RV64, but maybe it's better to fix this for both riscv and all future arches by removing the ifdefs related to TARGET_##_OS within this file and replacing the `uint32_t`/`uint64_t`s below with `uintptr_t`? That way this file isn't CPU dependent at all.

**Standard disclaimer:** running on non-x86 arches is untested and not officially supported, even after this change. You and any other users are welcome to use it or contribute fixes for it regardless, but there's not much we can do for a niche platform we don't have.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 663261c945d36120524accff51ac03e4aaa6aa2f
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev a547d6a966a48e3fa9461cbadb03e0c7e98a01fc</li>
<li>SPVGEN: dev fa39b110650bc72fd7fda54af621e69306036888</li>
<li>XGL: dev 36c5637649089bf65d42c36b431f47c170b57276</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 007e2c31e995541d6c0a91db17044e3da946c6ed</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/148239)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 38010/67195 (56.6%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 29185/67195 (43.4%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 8895/13849 (64.2%)</li>
<li><details><summary>Failed: 1/13849 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.spec_constant.graphics.geometry.composite.array.array_bvec2
Stack trace: Script:
Crash

```
</p></details></li>

<li>Not Supported: 4953/13849 (35.8%)</li><li>Warnings: 0/13849 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39069/67195 (58.1%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 28126/67195 (41.9%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by r-value** [comment]
Hi @JakeMerdichAMD, thank you for your advise! I've pushed a commit implementing that but test summary shows 1 test failing. Does it matter? Should I revert the commit?

**Comment by JaxLinAMD** [comment]
retest this please ( token to trigger test again)

**Comment by amdvlk-admin** [comment]
### Test summary for commit 663261c945d36120524accff51ac03e4aaa6aa2f
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev a547d6a966a48e3fa9461cbadb03e0c7e98a01fc</li>
<li>SPVGEN: dev fa39b110650bc72fd7fda54af621e69306036888</li>
<li>XGL: dev 36c5637649089bf65d42c36b431f47c170b57276</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 007e2c31e995541d6c0a91db17044e3da946c6ed</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/201585)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 38010/67195 (56.6%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 29185/67195 (43.4%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 37848/67195 (56.3%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 29347/67195 (43.7%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39069/67195 (58.1%)</li>
<li>Failed: 0/67195 (0.0%)</li>
<li>Not Supported: 28126/67195 (41.9%)</li><li>Warnings: 0/67195 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
