### PR TITLE
Replace DRI2 calls with DRM to fix Xwayland support

### PR DESCRIPTION
**Pull request by FelixBellaby**
The first commit fixes dri3Loader.py  drmLoader.py  procAnalysis.py in tools/generate/offline to make them generate the src/core/os/lnx/drmLoader.* and src/core/os/lnx/dri3/dri3Loader.* files correctly.

The second commit removes the DRI2 calls from dri3WindowSystem.cpp because DRI2 is unsupported on Xwayland and making DRI2 calls leads to segfaults during later DRI3 calls (on Ubuntu 18.04). The commit replaces the effect of the DRI2 calls using DRM calls. However, you might consider removing the DRM calls as well, since lnxDevice.cpp would be a better place to handle the KMD capabilities. This commit also alters the API footprint in the *.proc files and regenerates the related loader files.

### CODE REVIEW

**Comment by davidmaoamd** [comment]
Thanks for providing the patch.
Regarding to the first commit, the script has already been fixed internally.
For the second commit to drop the dri2 calls, we would like to keep it so that we could still identify the ddx vendor.  Instead, we will make he dri2 APIs optional for the AMDVLK, and everything should just work fine if dri2 library is not available in the system. 
Is it ok for you?

**Comment by FelixBellaby** [comment]
There is really no point in using DRI2 to get the name of the driver,
because xserver side of DRI2 does is call drmGetVersion to get the name
of the kernel driver. See https://cgit.freedesktop.org/xorg/xserver/tre
e/hw/xfree86/dri2/dri2.c in the xserver code:
static char *
dri2_probe_driver_name(ScreenPtr pScreen, DRI2InfoPtr info)
{
#ifdef WITH_LIBDRM
    int i, j;
    char *driver = NULL;
    drmDevicePtr dev;

    /* For non-PCI devices and drmGetDevice fail, just assume that
     * the 3D driver is named the same as the kernel driver. This is
     * currently true for vc4 and msm (freedreno).
     */
    if (drmGetDevice(info->fd, &dev) || dev->bustype != DRM_BUS_PCI) {
        drmVersionPtr version = drmGetVersion(info->fd);

        if (!version) {
            xf86DrvMsg(pScreen->myNum, X_ERROR,
                       "[DRI2] Couldn't drmGetVersion() on non-PCI
device, "
                       "no driver name found.\n");
            return NULL;
        }

        driver = strndup(version->name, version->name_len);
        drmFreeVersion(version);
        return driver;
    }
...#else   return NULL#endif}
drmGetVersion relies on the DRM_IOCTL_VERSION ioctl call to get the
version. This IOCTL in implemented in the amdgpu kernel code and gives
you direct access to the driver name by the most reliable possible
means. (This is a slight simplification as dri2_probe_driver_name also
looks for the name of the PCI driver, but this ultimately makes no
difference as the amdgpu kernel code returns the same name for the PCI
driver and the kms/drm driver).
The big disadvantage with using DRI2 to get this information is that it
will not work on the Xwayland xorg server and has no hope of working on
another platform like wayland itself. You are just saddling yourself
with an unnecessary problem fro the future.
If you insist on continuing to use DRI2 then you must check that it is
supported before using it. You check for DRI3 in the function
Dri3WindowSystem::IsextensionSupported using the following code:
pReply = m_dri3Procs.pfnXcbGetExtensionData(m_pConnection,
m_dri3Loader.GetXcbDri3Id());
To check from DRI2 then you would need access to the GetXcbDri2Id
function adding the following line to dri3WindowSystems.proc:
libxcb-dri2.so.0    @var xcb_extension_t xcb_dri2_id

And you could then add the line:

 pReply = m_dri3Procs.pfnXcbGetExtensionData(m_pConnection,
m_dri3Loader.GetXcbDri2Id());
to Dri3WindowSystem::IsExtensionSupported in dri3WindowSystem.cpp,
etc..

**Comment by davidmaoamd** [comment]
The reason we have to use DRI2 is that we actually have two DDX driver for the single device.
One is released with pro-package, which would explicitly set the driver name to "amdgpu".
The upstream version of ddx or mode setting driver will query the kernel to set the driver name.
Thus we need this information to make a call about whether to enable some features, like free-sync.

But your point about checking whether DRI2 extension is supported before sending request sounds like a good idea to me.
Do you want to make a change or I can help to submit internally then push out in the following release?
Thanks.

**Comment by FelixBellaby** [comment]
I had not realised that you were making use of the divergence between
the DRI2 names for the xf86-video-amdgpu DDX ("radeonsi") and amdgpu-
pro DDX ("amdgpu"). Hopefully, this is a stop gap measure while the
amdgpu-pro DDX specific code is moved into the kernel. It would not
help AMD sales to restrict access to features like free-sync to an ever
decreasing circle of amdgpu-pro/xserver users.I will put together a
pull request to check for support for the DRI2 extension out of the
code that I have here.
Thanks,

**Comment by davidmaoamd** [comment]
Yes. You are right about the harm of divergence and we are on the way to bridge the gap.
Thanks.

**Comment by FelixBellaby** [comment]
I have put in a pull request to GPUOPEN-DRivers/pal to implement the
DRI2 check now. I have checked it farily extensively without incident
on Xorg and Xwayland using Ubuntu 18.04.
Thanks

**Pull request closed without merging**
