### PR TITLE
Removed unused local variable in PerfTrace for gfx6 and gfx9

### PR DESCRIPTION
**Pull request by ardacoskunses**
NumShaderEngines does not seem to be used locally.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JacobHeAMD** [comment]
ok to test

**Comment by JacobHeAMD** [comment]
test this please

**Comment by amdvlk-admin** [comment]
Test results for commit 1666d3ef23e702e0975e72922485d3ad4fa391aa:<br/><br/>Test run totals:<br/>Passed:        183806/340842 (53.9%)<br/>Failed:        4/340842 (0.0%)<br/>Not supported: 157031/340842 (46.1%)<br/>Warnings:      1/340842 (0.0%)<br/><br/><details><summary>Expand for test failures</summary><br/>FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_src_transfer_dst.1024<br/>Stack trace: 14:BufferCopyToImage Result differs from reference, Expected: 0x0000003b, Got: 0x0000000d, At offset: 0<br/><br/>FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_src_transfer_dst.8192<br/>Stack trace: 14:BufferCopyToImage Result differs from reference, Expected: 0x0000003b, Got: 0x0000000d, At offset: 0<br/><br/>FAILURE: dEQP-VK.memory.pipeline_barrier.transfer_src_transfer_dst.65536<br/>Stack trace: 10:BufferCopyToBuffer Result differs from reference, Expected: 0x00000014, Got: 0x00000059, At offset: 24384<br/><br/>FAILURE: dEQP-VK.memory.pipeline_barrier.all_device.65536<br/>Stack trace: 5:SubmitRenderPass Image comparison failed</details>

**Comment by jinjianrong** [comment]
retest this please

**Pull request merged**
