### PR TITLE
Add branch prediction guides to PAL assertions

### PR DESCRIPTION
**Pull request by gflegar**
We observed ~2% performance improvement (depending on the workload), in builds with assertions enabled.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JakeMerdichAMD** [comment]
Ok to test.

Looks good to me, only nit is that PAL_HAS_BUILTIN should probably live next to PAL_HAS_CPP_ATTR in palUtil.h for consistency.

We also generally assume that all code in asserts get compiled out in shipped builds-- I would not be surprised if we needed to squash a few places for performance where we make read-only system calls or volatile memory accesses as well, which don't get optimized away because they are "side effects" even if they don't actually have an effect. That's not the case for 99% of it, though, and I wouldn't be overly concerned.

**Comment by JaxLinAMD** [comment]
ok to test

**Comment by JaxLinAMD** [comment]
build failure:
11:02:45  /jenkins/workspace/open-source/pal-github-pr/driver_build/drivers/pal/src/core/libInit.cpp:67:5: error: static assertion failed: The specified PAL_CLIENT_INTERFACE_MAJOR_VERSION is not supported.
11:02:45       static_assert((PAL_CLIENT_INTERFACE_MAJOR_VERSION >= PAL_MINIMUM_INTERFACE_MAJOR_VERSION) &&

**Comment by Flakebi** [comment]
I guess rebasing on top of `dev` should fix this build failure?

**Comment by JakeMerdichAMD** [comment]
Internal tests are also failing here (line number might be off due to internal/external differences): 

```
[2021-07-14T23:06:19.880Z] /jenkins/workspace/vulkan/vulkan-psdb/driver_build_gh/pal/src/core/os/amdgpu/amdgpuDevice.cpp: In static member function ‘static Pal::Result Pal::Amdgpu::Device::ParseClkInfo(const char*, Pal::Amdgpu::Device::ClkInfo*, Pal::uint32*)’:
[2021-07-14T23:06:19.880Z] /jenkins/workspace/vulkan/vulkan-psdb/driver_build_gh/pal/inc/util/palAssert.h:17:59: error: invalid conversion from ‘const char*’ to ‘long int’ [-fpermissive]
[2021-07-14T23:06:19.880Z]  #define PAL_PREDICT_FALSE(expr) __builtin_expect((expr), 0)
[2021-07-14T23:06:19.880Z]                                                            ^
[2021-07-14T23:06:19.881Z] /jenkins/workspace/vulkan/vulkan-psdb/driver_build_gh/pal/inc/util/palAssert.h:180:9: note: in expansion of macro ‘PAL_PREDICT_FALSE’
[2021-07-14T23:06:19.881Z]      if (PAL_PREDICT_FALSE(_expr))                                                               \
[2021-07-14T23:06:19.881Z]          ^~~~~~~~~~~~~~~~~
[2021-07-14T23:06:19.881Z] /jenkins/workspace/vulkan/vulkan-psdb/driver_build_gh/pal/inc/util/palAssert.h:187:26: note: in expansion of macro ‘PAL_ALERT_MSG’
[2021-07-14T23:06:19.881Z]  #define PAL_ALERT(_expr) PAL_ALERT_MSG(_expr, "%s", "Unknown")
[2021-07-14T23:06:19.881Z]                           ^~~~~~~~~~~~~
[2021-07-14T23:06:19.882Z] /jenkins/workspace/vulkan/vulkan-psdb/driver_build_gh/pal/src/core/os/amdgpu/amdgpuDevice.cpp:5430:17: note: in expansion of macro ‘PAL_ALERT’
[2021-07-14T23:06:19.882Z]                  PAL_ALERT("read pp_dpm_clk info error");
[2021-07-14T23:06:19.882Z]                  ^
[2021-07-14T23:06:19.882Z] <built-in>: note:   initializing argument 1 of ‘long int __builtin_expect(long int, long int)’
```

Looks like this needs to be changed to PAL_ALERT_ALWAYS_MSG.

**Comment by amdvlk-admin** [comment]
### Test summary for commit 03c39103ad171e271aa022b46a72485eca7630da
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev 72afd4ae01e3f5c043dbd2dfac57833408ac3f6b</li>
<li>SPVGEN: dev bb3da8bc00bcf4373d563bf9b3c74a80a8b28fe6</li>
<li>XGL: dev 5dbd470d8c1cbf8ee5d9a1204ba23a2fbf88a242</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 01f326c1e88cbf80e50a631ea0ce61a57152a7c0</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/227984)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31680/56996 (55.6%)</li>
<li>Failed: 0/56996 (0.0%)</li>
<li>Not Supported: 25316/56996 (44.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31677/56996 (55.6%)</li>
<li>Failed: 0/56996 (0.0%)</li>
<li>Not Supported: 25319/56996 (44.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32051/56996 (56.2%)</li>
<li>Failed: 0/56996 (0.0%)</li>
<li>Not Supported: 24945/56996 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34932/56996 (61.3%)</li>
<li>Failed: 0/56996 (0.0%)</li>
<li>Not Supported: 22064/56996 (38.7%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 7a9c336bc442e00acd0fb914f25a9249e666dcb7
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev 72afd4ae01e3f5c043dbd2dfac57833408ac3f6b</li>
<li>SPVGEN: dev bb3da8bc00bcf4373d563bf9b3c74a80a8b28fe6</li>
<li>XGL: dev 5dbd470d8c1cbf8ee5d9a1204ba23a2fbf88a242</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 01f326c1e88cbf80e50a631ea0ce61a57152a7c0</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/227984)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31680/56996 (55.6%)</li>
<li>Failed: 0/56996 (0.0%)</li>
<li>Not Supported: 25316/56996 (44.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31677/56996 (55.6%)</li>
<li>Failed: 0/56996 (0.0%)</li>
<li>Not Supported: 25319/56996 (44.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32051/56996 (56.2%)</li>
<li>Failed: 0/56996 (0.0%)</li>
<li>Not Supported: 24945/56996 (43.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34932/56996 (61.3%)</li>
<li>Failed: 0/56996 (0.0%)</li>
<li>Not Supported: 22064/56996 (38.7%)</li>
</ul></details>


</ul></details>

**Comment by gflegar** [comment]
Rebased on dev, changed the problematic `PAL_ALERT` to `PAL_ALERT_ALWAYS_MSG`, and moved `PAL_HAS_BUILTIN` definition to `palUtil.h`.

**Comment by JaxLinAMD** [comment]
@JakeMerdichAMD  can you approve it? then I can merge it.

**Comment by gflegar** [comment]
Any update on this?

**Review by JakeMerdichAMD — APPROVED** [review]
Sorry on delay, was out of office last week. Merging now.

**Comment by Flakebi** [comment]
I’m not quite sure why this is happening, but this patch breaks ignoring assertions with `HardAssert,0` in `amdVulkanSettings.cfg` in debug mode.

**Comment by JakeMerdichAMD** [comment]
@Flakebi, that's rather critical, I'll dig into that ASAP.

**Comment by JakeMerdichAMD** [comment]
So, found the issue. Pop quiz: what is wrong with `PAL_ASSERT(*pUnderrun++ == UnderrunSentinel);` when you use the argument for both the conditional and `PAL_ANALYSIS_ASSUME` (which still runs the code and does any side effects on linux)?

Expect a hotfix that only evaluates the argument once shortly.

**Pull request merged**
