### PR TITLE
Add remote reliable (TCP) socket support in gpuopen

### LINKED ISSUE #73: Communication through gpuopen can be unreliable for non-lan usage
Doing RGP captures or using other features through gpuopen protocols over UDP when connecting to cloud servers can be unreliable.

### PR DESCRIPTION
**Pull request by jfthibert**
Resolves #73

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JaxLinAMD** [comment]
ok to test

**Comment by JaxLinAMD** [comment]
@JakeMerdichAMD  is it up to you to review this?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 3294ac8af20657fbd8a31b3bf1170370147846a1
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev a315e405b109c42f49111447012b17b5566db2b6</li>
<li>SPVGEN: dev 79f8e32dd7242d7d34fa0074f761c9d794f11811</li>
<li>XGL: dev 5c3c2dd430222cdf1b46c9d385e9c6c5e89604e1</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 0cb96bc82ca13e0fef3684a4ac8f6eff50bce257</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/228128)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31146/57032 (54.6%)</li>
<li>Failed: 0/57032 (0.0%)</li>
<li>Not Supported: 25886/57032 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31145/57032 (54.6%)</li>
<li>Failed: 0/57032 (0.0%)</li>
<li>Not Supported: 25887/57032 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31285/57032 (54.9%)</li>
<li>Failed: 0/57032 (0.0%)</li>
<li>Not Supported: 25747/57032 (45.1%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34853/57032 (61.1%)</li>
<li>Failed: 0/57032 (0.0%)</li>
<li>Not Supported: 22179/57032 (38.9%)</li>
</ul></details>


</ul></details>

**Comment by JakeMerdichAMD** [comment]
Reaching out internally to the right folks to review this.

**Pull request closed without merging**
