### PR TITLE
Fix warning -Werror=extra of issue #62

### PR DESCRIPTION
**Pull request by JaxLinAMD**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 9298f322c01a585ed3aafd19fcce195b1a3b3a77
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev f5120c4c234eee413e87c1d34ca50ac0dad4c471</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev f67223913cf046cb65adcc3bd3f06c6ad232f150</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 661ac9b7d0d9edcbd07bd1b40c334934ff2297ac</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/222275)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30438/55574 (54.8%)</li>
<li>Failed: 0/55574 (0.0%)</li>
<li>Not supported: 25136/55574 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30437/55574 (54.8%)</li>
<li>Failed: 0/55574 (0.0%)</li>
<li>Not supported: 25137/55574 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30630/55553 (55.1%)</li>
<li><details><summary>Failed: 1/55553 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.device_set_reset
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, DE_NULL): VK_ERROR_UNKNOWN at vktSynchronizationBasicEventTests.cpp:117

```
</p></details></li>

<li>Not supported: 24922/55553 (44.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34000/55574 (61.2%)</li>
<li><details><summary>Failed: 1/55574 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.device_set_reset
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, DE_NULL): VK_ERROR_UNKNOWN at vktSynchronizationBasicEventTests.cpp:117

```
</p></details></li>

<li>Not supported: 21573/55574 (38.8%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit d9cb375a7c0f02c1cc963032b3979dac8088874a
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev f5120c4c234eee413e87c1d34ca50ac0dad4c471</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev f67223913cf046cb65adcc3bd3f06c6ad232f150</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 661ac9b7d0d9edcbd07bd1b40c334934ff2297ac</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/222275)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30438/55574 (54.8%)</li>
<li>Failed: 0/55574 (0.0%)</li>
<li>Not supported: 25136/55574 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30437/55574 (54.8%)</li>
<li>Failed: 0/55574 (0.0%)</li>
<li>Not supported: 25137/55574 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30630/55553 (55.1%)</li>
<li><details><summary>Failed: 1/55553 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.device_set_reset
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, DE_NULL): VK_ERROR_UNKNOWN at vktSynchronizationBasicEventTests.cpp:117

```
</p></details></li>

<li>Not supported: 24922/55553 (44.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34000/55574 (61.2%)</li>
<li><details><summary>Failed: 1/55574 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.device_set_reset
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, DE_NULL): VK_ERROR_UNKNOWN at vktSynchronizationBasicEventTests.cpp:117

```
</p></details></li>

<li>Not supported: 21573/55574 (38.8%)</li>
</ul></details>


</ul></details>

**Review by JakeMerdichAMD — COMMENTED** [review]
Belated 'Ship It' in terms of code review; thanks for fixing this! I gave implicit approval in #63 as well.

**Pull request merged**
