### PR TITLE
Unused local variable cleanup, general swipe for pal core gfx6 and gfx9

### PR DESCRIPTION
**Pull request by ardacoskunses**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JacobHeAMD** [comment]
ok to test

**Comment by JacobHeAMD** [comment]
test this please

**Comment by amdvlk-admin** [comment]
Test results for commit d253ee6d9b725676da759bca35e0c23c10af6783:<br/><br/>

**Comment by JacobHeAMD** [comment]
retest this please

**Pull request merged**
